name: clean_dart_surveys
description: Pesquisa para Devs.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  faker: ^2.0.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
